name: Deploy Laravel Application to Production Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3  # 🔹 Use correct PHP version

    - name: Install Composer Dependencies
      run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.8.0  # 🔹 Use stable LTS version

    - name: Install NPM Dependencies
      run: npm ci  # 🔹 Faster & more reliable than `npm install`

    - name: Build Frontend Assets
      run: npm run build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vite-build
        path: public/build

    - name: Synchronize Files To Server
      uses: easingthemes/ssh-deploy@v5.1.0
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "."  # 🔹 Only sync built assets
        REMOTE_HOST: ${{ secrets.VPS_HOST }}
        REMOTE_USER: ${{ secrets.VPS_USER }}
        TARGET: "/home/u890207559/public_html/public/build"
        REMOTE_PORT: "65002"

    - name: Deploy Application via SSH
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 65002
        script: |
            cd /home/u890207559/public_html
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan cache:clear
            php artisan migrate --force
